# Terminal
bindsym $mod+Return exec alacritty

# Kill
bindsym $mod+Shift+q kill

# Launcher
bindsym $mod+d       exec --no-startup-id rofi -show drun
bindsym $mod+space   exec --no-startup-id rofi -show combi
bindsym $mod+Tab     exec --no-startup-id rofi -show window

# File manager
bindsym $mod+e exec --no-startup-id thunar

# Focus
bindsym $mod+h focus left
bindsym $mod+j focus down
bindsym $mod+k focus up
bindsym $mod+l focus right
bindsym $mod+Left  focus left
bindsym $mod+Down  focus down
bindsym $mod+Up    focus up
bindsym $mod+Right focus right

# Move
bindsym $mod+Shift+h move left
bindsym $mod+Shift+j move down
bindsym $mod+Shift+k move up
bindsym $mod+Shift+l move right
bindsym $mod+Shift+Left  move left
bindsym $mod+Shift+Down  move down
bindsym $mod+Shift+Up    move up
bindsym $mod+Shift+Right move right

# Layout
bindsym $mod+f         fullscreen toggle
bindsym $mod+s         layout stacking
bindsym $mod+w         layout tabbed
bindsym $mod+Shift+e   layout toggle split
bindsym $mod+Shift+space floating toggle
bindsym $mod+a         focus parent

# i3 control
bindsym $mod+Shift+c reload
bindsym $mod+Shift+r restart
bindsym $mod+Shift+p exec "i3-nagbar -t warning -m 'You pressed the exit shortcut. Do you really want to exit i3? This will end your X session.' -B 'Yes, exit i3' 'i3-msg exit'"

# Resize mode
bindsym $mod+r mode "resize"

# Volume
bindsym XF86AudioRaiseVolume exec --no-startup-id pactl set-sink-volume @DEFAULT_SINK@ +10% && $refresh_i3status
bindsym XF86AudioLowerVolume exec --no-startup-id pactl set-sink-volume @DEFAULT_SINK@ -10% && $refresh_i3status
bindsym XF86AudioMute        exec --no-startup-id pactl set-sink-mute @DEFAULT_SINK@ toggle && $refresh_i3status
bindsym XF86AudioMicMute     exec --no-startup-id pactl set-source-mute @DEFAULT_SOURCE@ toggle && $refresh_i3status

# Brightness
bindsym XF86MonBrightnessUp   exec --no-startup-id brightnessctl set +5%
bindsym XF86MonBrightnessDown exec --no-startup-id brightnessctl set 5%-

# Screenshots - file
bindsym Print             exec maim "/home/$USER/Pictures/$(date).jpg"
bindsym $mod+Print        exec maim --window $(xdotool getactivewindow) "/home/$USER/Pictures/$(date).jpg"
bindsym Shift+Print       exec maim --select "/home/$USER/Pictures/$(date).jpg"

# Screenshots - clipboard
bindsym Ctrl+Print        exec maim | xclip -selection clipboard -t image/png
bindsym Ctrl+$mod+Print   exec maim --window $(xdotool getactivewindow) | xclip -selection clipboard -t image/png
bindsym Ctrl+Shift+Print  exec maim --select | xclip -selection clipboard -t image/png
